version: '3.8'
services:
  vote:
    build: ./vote
    ports:
      - "5000:80"
    networks:
      - votenet
  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - votenet
  worker:
    build: ./worker
    networks:
      - votenet
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:7-alpine
    networks:
      - votenet
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # ¡Solo para desarrollo!
    networks:
      - votenet

networks:
  votenet:
