name: Integración Continua (CI)

on:
  # Se dispara en pushes a cualquier rama que NO sea main
  push:
    branches-ignore:
      - 'main'
  # También en Pull Requests hacia main
  pull_request:
    branches:
      - 'main'

jobs:
  tests-y-build:
    runs-on: ubuntu-latest # Este job puede correr en un runner de GitHub

    steps:
    - name: 📥 Clonar el código
      uses: actions/checkout@v4

    - name: 🐍 Simular tests para 'vote' (Python)
      run: echo "✅ Tests de Python para 'vote' pasaron."

    - name: 📦 Simular tests para 'result' (Node.js)
      run: echo "✅ Tests de Node.js para 'result' pasaron."

    - name: 🧠 Simular tests para 'worker' (Node.js)
      run: echo "✅ Tests de Node.js para 'worker' pasaron."

    - name: 🐳 Construir imágenes Docker con Docker Compose
      # Este paso verifica que todos los Dockerfiles son válidos y construyen las imágenes
      run: docker-compose build
