# Archivo: .github/workflows/deploy.yml
# Versión corregida para apuntar a 'roxs-voting-app'

name: Despliegue Continuo (CD)

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  integracion-continua:
    uses: ./.github/workflows/ci.yml

  desplegar:
    needs: integracion-continua
    runs-on: self-hosted

    steps:
    - name: 📥 Clonar el código en el runner
      uses: actions/checkout@v4

    - name: 🛑 Parar servicios anteriores
      # LA CORRECCIÓN: Apuntamos a la carpeta correcta.
      working-directory: ./roxs-voting-app
      run: docker-compose down -v --remove-orphans || true

    - name: 🚀 Construir y levantar nuevos servicios
      # LA CORRECCIÓN: Apuntamos a la carpeta correcta.
      working-directory: ./roxs-voting-app
      run: docker-compose up -d --build

    - name: 🩺 Verificar que la app de votación responde
      run: |
        sleep 10 # Dar tiempo a que los servicios levanten
        echo "Verificando el estado de la aplicación de votación..."
        # El puerto 5000 es el que definimos para el servicio 'vote'
        curl -f http://localhost:5000
