name: CI Pipeline

on:
  push:
    branches: [ develop, main ]
    paths:
      - 'voting-app/roxs-voting-app/**'
  pull_request:
    branches: [ develop, main ]
    paths:
      - 'voting-app/roxs-voting-app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and test Vote app
      run: |
        cd voting-app/roxs-voting-app
        docker build -t vote-test ./vote
        echo "✅ Vote app built Terminada"
        
    - name: Build and test Result app
      run: |
        cd voting-app/roxs-voting-app
        docker build -t result-test ./result
        echo "✅ Result app built Terminada"
        
    - name: Build and test Worker app
      run: |
        cd voting-app/roxs-voting-app
        docker build -t worker-test ./worker
        echo "✅ Worker app built Terminada"
      
    - name: Integration test with Docker Compose
      run: |
        cd voting-app/roxs-voting-app
        docker compose -f docker-compose.yml up -d
        sleep 30
        
        # Basic health checks
        curl -f http://localhost:8080/ || exit 1
        curl -f http://localhost:3000/ || exit 1
        
        docker compose -f docker-compose.yml down -v
        echo "✅ Integration tests OK"