name: CI - Build y Push de Imágenes Docker

on:
  push:
    branches: [ "develop" ] # Se activa con pushes a la rama de desarrollo
  pull_request:
    branches: [ "main" ] # También se activa al crear un PR hacia main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y pushear VOTE
        uses: docker/build-push-action@v5
        with:
          context: ./voting-app/roxs-voting-app/vote
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest

      - name: Construir y pushear WORKER
        uses: docker/build-push-action@v5
        with:
          context: ./voting-app/roxs-voting-app/worker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest

      - name: Construir y pushear RESULT
        uses: docker/build-push-action@v5
        with:
          context: ./voting-app/roxs-voting-app/result
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/result:latest
