name: CD - Despliegue a Staging

on:
  workflow_run:
    workflows: ["CI Pipeline"] # Debe coincidir con el 'name:' de tu ci.yml
    types: [completed]
    branches: [develop]

jobs:
  deploy:
    # Solo se ejecuta si el workflow anterior fue exitoso
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # ¡Aquí usamos tu runner!
    runs-on: self-hosted-staging 

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar stack de Staging con el script
        run: |
          echo "Ejecutando script de despliegue para Staging..."
          cd ./voting-app/roxs-voting-app/
          ./scripts/deploy.sh staging