name: Deploy con Docker Compose

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: 📥 Clonar el código en el runners
      uses: actions/checkout@v4

    # --- ¡AQUÍ ESTÁ LA SOLUCIÓN! ---
    # Añadimos un nuevo paso para instalar docker-compose si no existe.
    - name: 🔧 Instalar Docker Compose
      run: |
        # Descargamos el binario de Docker Compose v1 (versión estable)
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        # Le damos permisos de ejecución
        sudo chmod +x /usr/local/bin/docker-compose

    - name: 🛑 Parar servicios anteriores (si existen)
      working-directory: ./mi-app
      run: docker-compose down -v --remove-orphans || true

    - name: 🚀 Construir y levantar nuevos servicios
      working-directory: ./mi-app
      run: docker-compose up -d --build

    - name: 🩺 Verificar que la app responde
      run: |
        sleep 5
        echo "Verificando el estado de la aplicación..."
        curl -f http://localhost:3000
