name: Deploy con Docker Compose

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    # Le decimos que use tu runner personal
    runs-on: self-hosted

    steps:
    - name: 📥 Clonar el código en el runner
      uses: actions/checkout@v4

    - name: 🛑 Parar servicios anteriores (si existen)
      # La solución: nos movemos a la carpeta 'mi-app' primero
      working-directory: ./mi-app
      # El '|| true' evita que el workflow falle si no hay nada que parar
      run: docker-compose down -v --remove-orphans || true

    - name: 🚀 Construir y levantar nuevos servicios
      # Nos aseguramos de estar en la misma carpeta para este paso también
      working-directory: ./mi-app
      # Usamos 'up -d --build' para construir y levantar en un solo paso eficiente
      run: docker-compose up -d --build

    - name: 🩺 Verificar que la app responde
      # Damos unos segundos para que el servidor inicie
      run: |
        sleep 5
        echo "Verificando el estado de la aplicación..."
        curl -f http://localhost:3000
