name: CI/CD Pipeline para Voting App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- TRABAJO 1: CONSTRUIR IMÁGENES Y SUBIRLAS A DOCKER HUB ---
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # --- CORRECCIÓN DE RUTA ---
      - name: Build and push VOTE
        uses: docker/build-push-action@v5
        with:
          context: ./1-voting-app-docker-compose/roxs-voting-app/vote
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest

      # --- CORRECCIÓN DE RUTA ---
      - name: Build and push WORKER
        uses: docker/build-push-action@v5
        with:
          context: ./1-voting-app-docker-compose/roxs-voting-app/worker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest

      # --- CORRECCIÓN DE RUTA ---
      - name: Build and push RESULT
        uses: docker/build-push-action@v5
        with:
          context: ./1-voting-app-docker-compose/roxs-voting-app/result
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/result:latest

  # --- TRABAJO 2: DESPLEGAR LA APLICACIÓN EN TU SERVIDOR ---
  deploy:
    needs: build-and-push
    runs-on: self-hosted
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Desplegar con Docker Compose
        run: |
          # --- CORRECCIÓN DE RUTA ---
          cd voting-app/roxs-voting-app
          docker compose pull
          docker compose up -d
