---
- name: Tarea práctica Día 6 - Configuración de servidor web
  hosts: webservers
  become: yes
  
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Iniciar y habilitar Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copiar página personalizada
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Crear usuario deploy
      user:
        name: deploy
        groups: sudo
        append: yes
        password: "{{ 'miPassword123' | password_hash('sha512') }}"
        shell: /bin/bash

    - name: Configurar acceso SSH para usuario deploy
      authorized_key:
        user: deploy
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Instalar ufw
      apt:
        name: ufw
        state: present

    - name: Habilitar firewall
      ufw:
        state: enabled
        policy: deny

    - name: Permitir puertos 22, 80, 443
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22
        - 80
        - 443

    - name: Crear página motivacional
      copy:
        content: "<h1>¡Día 6 completado! Sigue con #90DaysOfDevOps 🚀</h1>"
        dest: /var/www/html/motivacion.html
        mode: '0644'
